### ISSUE TITLE
Higher Resolution + SVG

### ISSUE THREAD

**Issue by ZanderBrown** [raspberrypi/pix-icons#1]
I like these new icons, they help make the pi more unique and identifiable

However i have come to notice that the icons are only available in relatively low resolution meaning icons in about dialogs for example are rather pixelated (and not in a good way 😄 )

I would suggest the icons are made in SVG format then exported to all the various sizes to make these icons look their best wherever they are used

**Comment by spl237** [comment]
SVG format does not give the best results for all sizes; these icons are optimised at the pixel level for the standard icon sizes (16/24/32). We are already planning to add SVG versions for the larger sizes at some point, as they do scale better for larger sizes than these.
